### ISSUE TITLE
发展方向

### ISSUE THREAD

**Issue by LeafYeeXYZ** [LeafYeeXYZ/BNUCourseGetter#2]
- [x] 补全抢专业课的功能（教务系统有个bug：按开课计划选课那里, 点开一门课程后, 在弹出窗口中点击刷新无效, 相同的功能在按时间选课那里是正常的）
- [x] 修复或改善内存泄漏问题（playwright所用的内存会随着刷新次数逐渐增加, 暂时没找到好的解决办法；用单线程蹲课或定期重启应用可改善）
- [x] 新增单线程蹲课模式
- [x] 加入抢/蹲多门课的功能
- [x] 同时选课数量太多时弹出警告
- [x] 画一个应用图标
- [x] 优化一下UI

**Comment by LeafYeeXYZ** [comment]
- 你怎么知道我抢到网课了

**Comment by wander8825** [comment]
谢谢大佬。
但为什么一点上边框就会闪退呀？

**Comment by wander8825** [comment]
一点小小的疑问：请问为什么点“开始”并确认后，马上就闪退了呢？

**Comment by LeafYeeXYZ** [comment]
> 一点小小的疑问：请问为什么点“开始”并确认后，马上就闪退了呢？

请问您的系统和使用的小鸦抢课版本是什么? 可以下载最新版本, 并 `以管理员权限运行` 试试

**Comment by wander8825** [comment]
windows系统和xyqk-windows-amd64-installer.exe，现在可以用啦（开心脸），希望还能蹲到网课（流泪）

**Comment by LeafYeeXYZ** [comment]
蹲专业课已完成, 现阶段速度较慢(对蹲课来说倒是不影响), 未来可能会改进!
