### ISSUE TITLE
程序无法登录数字京师

### ISSUE THREAD

**Issue by yhFenrirKK** [LeafYeeXYZ/BNUCourseGetter#5]
你好呀，我使用你的小鸦抢课，发现程序在打开自带的谷歌浏览器的数字京师登录页面后，浏览器会显示“无法访问此网站”因为链接超时，我试着复制了网上搜索的数字京师官网粘贴进程序自带的谷歌浏览器里，虽然能够正常登录，但是抢课的程序无法正常进行，稍等一会后便会显示“检测到发生错误: playwright: timeout: Timeout 30000ms exceeded”，然后重启浏览器，一直这样死循环

**Comment by LeafYeeXYZ** [comment]
你好呀，请试一下关闭VPN（如果开了的话），并重新开关一下WIFI。我等下回宿舍自己也再试试

**Comment by LeafYeeXYZ** [comment]
我这边测试没问题! 之前好像没有别的同学反应过这个问题, 可能是你的网络环境问题, 请问你现在能稳定复现这个问题吗!

**Comment by yhFenrirKK** [comment]
是的，我这几天尝试都是这样，请问您在校内吗？我是住在校外，并未使用校园网，可能是这个原因？但是我在edge浏览器和Chrome浏览器输入数字京师的地址，都是可以正常登入和选课的。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年9月12日(周四) 晚上9:37
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [LeafYeeXYZ/BNUCourseGetter] 程序无法登录数字京师 (Issue #5)




 
我这边测试没问题! 之前好像没有别的同学反应过这个问题, 可能是你的网络环境问题, 请问你现在能稳定复现这个问题吗!

**Comment by LeafYeeXYZ** [comment]
啊是的！必须用校园网！我去修改一下使用说明强调一下，感谢你的issue！

**Comment by yhFenrirKK** [comment]
了解了！谢谢！



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年9月12日(周四) 晚上9:43
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [LeafYeeXYZ/BNUCourseGetter] 程序无法登录数字京师 (Issue #5)




 
啊是的！必须用校园网！我去修改一下使用说明强调一下，感谢你的issue！
